### ISSUE TITLE
Liste de dépendances "illégale" ds kde5 meta paquet

### ISSUE THREAD

**Issue by tnut** [NuTyX/kde5#1]
Uniquement les paquets de la collection kde5 doivent être présents

**Comment by Pierre-NuTyX** [comment]
fait

**Comment by tnut** [comment]
Oups, c'était sans doute pas assez clair, Les paquets que tu as commités dans extra doivent aller dans la collection kde5-extra pas dans la collection extra/graphic

**Comment by Pierre-NuTyX** [comment]
non ils n'ont rien a voir avec kde5 , c'est un client owncloud et sa dep 
qui peuvent fonctionner sous n'importe quel bureau , juste la dep a 
faire en qt4
