### ISSUE TITLE
Connexion à mail.google.com après le chargement de Plasma 5.7.1 ?

### ISSUE THREAD

**Issue by FredBezies** [NuTyX/kde5#18]
J'ai installé Plasma 5.7x avec le "trio" kde5, kde5-extra et sddm.

Une fois connecté et Plasma chargé, j'ai une boite de dialogue bizarre qui me demande un duo nom d'utilisateur et mot de passe pour mail.google.com ?

![mailgooglecom](https://cloud.githubusercontent.com/assets/8571419/16847227/409501fc-49f0-11e6-8438-7628beb07c0d.png)

Impossible de s'en débarrasser, elle revient à chaque fois. Est-ce lié aux outils de courrier électronique de Plasma ?

**Comment by Pierre-NuTyX** [comment]
Bonjour, 

C'est une demande d'un utilisateur que j'ai oublié de supprimer 
`del -a kdeplasma-applets-gmailfeed`
et reboot

**Comment by FredBezies** [comment]
Merci pour l'info :)

**Comment by tnut** [comment]
Pierre, déplace kdeplasma-applets-gmailfeed dans gui-extra histoire de ne
pas le virer inutilement

2016-07-14 18:37 GMT+02:00 FredBezies <notifications@github.com>:

**Comment by Pierre-NuTyX** [comment]
fait.
Le problème est qu'il y a des deps kde5 ...
Il faudrait voir comment l'installer sans qu'il se lance.
En attendant il est dans gui-extra
