### ISSUE TITLE
Problème de réseau sous Plasma 5.7.1 avec NetworkManager

### ISSUE THREAD

**Issue by FredBezies** [NuTyX/kde5#19]
J'ai installé Plasma 5.7x avec le "trio" kde5, kde5-extra et sddm.

Une fois connecté et Plasma chargé, je n'ai plus de connexion internet. J'ai donc essayé de désactiver, puis réactiver la connexion. En vain. J'ai un message d'erreur qui m'indique que je n'ai pas le droit de faire cela : 

`org.freedesktop.NetworkManager.network-control request failed : not authorized`

![networkmanagerplasma](https://cloud.githubusercontent.com/assets/8571419/16847395/2d41c6de-49f1-11e6-9504-5e0784d541ce.png)

Mauvaise manipulation de ma part ? Bug connu ?

**Comment by Pierre-NuTyX** [comment]
Rebonjour,

En attendant que ce soit réglé, mets toi en ip fixe et relance
(je l'avais oublié celui là)

**Comment by FredBezies** [comment]
Ok. Je prends note.

**Comment by Pierre-NuTyX** [comment]
merci de tes retours

**Comment by tnut** [comment]
2 choses à clarifier
   1. Y a-t'il vraiment pas de réseau  ou c'est juste networkmanager qui râle parce que son service est pas lancé ce qui est normal si la machine n'a pas redémarré entre l'install de kde5 et le lancement de kde5.
   2. Est-ce que la machine a été relancée entre l'install de kde5 et compère et son lancement ou est-tu passé par la commande:

        init5

Pour info, le fichier /etc/sysconfig/network  force l'un ou l'autre mode de connection

         man nutyx

Rubrique Le réseau

**Comment by FredBezies** [comment]
1) Les deux, mon colonel. J'ai fait installer Plasma (en utilisant les paquets listés dans le rapport), puis sudo reboot, et pas de réseau.

2) Oui, il y a eu redémarrage. J'ai essayé de forcer la main de l'installation, mais sans grande réussite. C'est le seul bug vraiment ennuyeux et bloquant sur lequel j'ai pu tomber.

**Comment by tnut** [comment]
Les compilations étant bcp plus pointues depuis la version 8.2. Une deps manquante ne pardonne plus. C'est corrigé. demain  après maj tout devrait rentrer dans l'ordre

**Comment by FredBezies** [comment]
Je testerai dès que possible.
