### ISSUE TITLE
qt5 est erroné ici et là

### ISSUE THREAD

**Issue by tnut** [NuTyX/kde5#2]
Sans doute la dernière version correcte 
https://github.com/NuTyX/kde5/blob/c7094becd59ce3de1e68f312c9f2fb93b6e1f50d/kde5/qt5/Pkgfile

**Comment by Pierre-NuTyX** [comment]
Non , déjà il manque à la fin mkdir -p $PKG/usr/bin  :-)

le dernier commit correspond a lfs , j'ai mis toutes les libs xorg comme 
indiqué, toutes les deps existantes dans NuTyX / paquets et enlevé skip 
webkit

**Comment by tnut** [comment]
croisons les doigts

**Comment by Pierre-NuTyX** [comment]
ben c'est mort

j'abandonne raz le bol

**Comment by Pierre-NuTyX** [comment]
je fais un dernier essai,

j'ai repris celui de kf5 et le make est passé :

la différence entre les deux étant la présence de la variable QTBINDIR=/

j'ai relancé de kde5 corrigé.

Je prends le kde5 parce qu'il y a pas mal d'erreur sur la partie après make

je croise les doigts pour

1/ que ça passe avec une vrai raison
2/ que mon proc crame pas ... il fait chaud et sensors n'est pas tres 
gentil avec ma tension
