### ISSUE TITLE
Demande integration kde5-extra dans kde5

### ISSUE THREAD

**Issue by Pierre-NuTyX** [NuTyX/kde5#20]
La gestion des dépendances devient de plus en plus compliqué entre kde5 et kde5-extra.
Etant donné que je ne connais pas grand monde qui installe uniquement kde5, ce serait beaucoup plus simple de tout réunir.
Au moins kf5 (framework) plasma et applications
On pourrais laisser dans extra tout ce qui n'est pas dans les 3 branches.

**Comment by tnut** [comment]
Ok, oui je comprends le problème, je regarde ce que je peux faire (faut modifier build-collection) pas de problèmes

**Comment by Pierre-NuTyX** [comment]
On peut garder kde5-extra pour des ports comme kamoso qui ne sont pas dans applications

**Comment by tnut** [comment]
Oui pas de problèmes pour moi, un port minimum suffit pour ne pas devoir modifier build-collection

**Comment by Pierre-NuTyX** [comment]
ok, dès que j'ai un peu de tranquillité je le fais.
