### ISSUE TITLE
le port qt5 peut être supprimé 

### ISSUE THREAD

**Issue by tnut** [NuTyX/kde5#3]
Soit il faut le supprimé soit il  va dans la collection kde5. Il sera à jour  dans la collection graphic

**Comment by Pierre-NuTyX** [comment]
oui bien sur

en fait c'est moi qui l'ai ajouté en copie, quand je fais un cards base 
-r et un for i in *; do rm ...*.tar ..., ça m’évite de recompiler qt5, 
en le recopiant apres :-)
