### ISSUE TITLE
Ne pas merge le pull request

### ISSUE THREAD

**Issue by Pierre-NuTyX** [NuTyX/kde5#8]
Kde a encore modifié plein de chose, ne merge rien pour le moment

Je te tiens au courant

**Comment by tnut** [comment]
ok je standby sur les deux branches 8.1 et master

**Comment by Pierre-NuTyX** [comment]
Voila c'est bon.
Etant donné le peu d’intérêt pour la suite kdepim, et l'apparition de nouvelle librairies dans la version 16.04.0, avec leur chapelet de dépendances qui évidement ne passent pas toutes ... j'ai tout mis dans rework.

Restent dans kde5-extra ce dont j'ai besoin.
